# appveyor.yml
version: "{build}"
image: Visual Studio 2022

environment:
  NODEJS_VERSION: "20"
  NEXT_TELEMETRY_DISABLED: "1"
  CI: "true"
  # If your build is heavy, uncomment:
  # NODE_OPTIONS: "--max_old_space_size=4096"

install:
  # AppVeyor helper to install Node on Windows images
  - ps: Install-Product node $env:NODEJS_VERSION
  - node -v
  - npm -v
  - npm ci

build_script:
  - npm run build

test_script:
  - npm test --if-present

artifacts:
  # Keep Next.js build output as artifact (useful for inspection)
  - path: .next
    name: next-build
  # If you do static export (next export), publish the "out" dir:
  - path: out\**
    name: static-export
    type: zip

cache:
  # Reuse deps when lockfile unchanged
  - node_modules -> package-lock.json
